### ISSUE TITLE
Percussive organ/explosion

### ISSUE THREAD

**Issue by terrac** [andyhall/wasgen#1]
There is an extraneous a  at the end of the first gain

[ { type: 'np', 
    freq: {  }, 
    gain: { v: 0.5, d: 0.7, s: 0 a} }, 
  { type: 'sine', target: '0.gain', 
    freq: { t: 0, f: 25.74, p: 1.45, q: 0.56 }, 
    gain: { v: 0.3, a: 0, h: 0, d: 0.3, s: 0 } }, 
  { type: 'lowpass', 
    freq: { t: 2, p: 0.25, q: 0.41 }, 
    gain: {  } }, 
]

**Comment by fenomas** [comment]
Hi, think I'd need some reproducing steps to do anything with this. Thanks!

**Comment by terrac** [comment]
I went to the demo and selected the percussive organ, then explosion.  Now I'm thinking I just accidentally typed a character because I can't reproduce it.
