### ISSUE TITLE
A440 .WAV Export for WASGEN?

### ISSUE THREAD

**Issue by NeuroNoNeuro** [andyhall/wasgen#2]
Such a nice set of tones pulled from the synth, very FM, very lo-fi and pretty.  Would be nice to have an export function to turn these into samples for music production!

**Comment by fenomas** [comment]
Hi, sorry I forgot to reply to this. It's not currently built in, but exporting to WAV can be done one level up using a offline audio context. 

For posterity, it's implemented in the `wafxr` demo - [this bit](https://github.com/andyhall/wafxr/blob/master/docs/demo.js#L658-L659) is the setup, then audio is [played into a buffer](https://github.com/andyhall/wafxr/blob/master/docs/demo.js#L676-L677), and then the buffer is [converted to wav](https://github.com/andyhall/wafxr/blob/master/docs/demo.js#L686-L690).

**Comment by NeuroNoNeuro** [comment]
Oh, no problem at all - life is super busy!  Thank you for replying :)  Good to know!

**Comment by NeuroNoNeuro** [comment]
Well, I do hope one day it'll have a .WAV exporter - I'm using two of the sounds in Renoise right now - it's just so General MIDI - beautiful, lonely.  I was able to capture the audio through Audio Hijack, then I spend a fair amount of time editing it :)

**Comment by fenomas** [comment]
@kirkmarkarian Are you generating your sounds through the [demo page](https://andyhall.github.io/wasgen/), or are you using wasgen as a dependency in your own code? Or something else?

**Comment by NeuroNoNeuro** [comment]
I use the demo page to generate the sound - I do not know how to code.  Once the demo page is loaded, I open up the Mac OS X Application called "Audio Hijack", and record from it - this picks up all the audio from my computer, web or otherwise.  Then I export that file from Audio Hijack, save to my desktop, and manipulate it within Renoise.

For the sake of speed, it would be easier for the non-coding end-user (me and others like me), to go to the demo page, play the sound, and possibly have the option to save that sound as a .WAV file (or other audio file).  Would save a few steps.  Like the [WAFXR demo page](https://andyhall.github.io/wafxr/), this would be nice!

**Comment by fenomas** [comment]
Hi, thanks that's very clear. I think I can set this up. But I need to think a little about the UI for how you specify what frequency and duration of sound you want to render.

How do you do frequencies currently, do you use the keyboard, or just hard-code them (like with `freq: 440`) and press the "play sound" button?

**Comment by NeuroNoNeuro** [comment]
Great!  For the greatest scope of sound, it would be ideal to have the option to choose the frequency range.  To have the capability to type in the frequency would save time; maybe have it set at 440 to begin with - if nobody wants to change anything, it'll output a sample at that frequency to begin with.  That's what I've been doing, just using what's there, because it's already fine.  But, if somebody REALLY wanted to make an entire sample set of every note, that would make this a possibility.

Thanks for helping with this - like WAFXR, this particular FM set of sounds is so unique.  I miss my old PII with Windows '95 and Cakewalk/MIDI because of this.  Those tones are so strange - beautiful!  I also enjoy the randomized hi-hats and various other cymbal sounds - they're so unrealistic that they have their own captivating sound.

**Comment by fenomas** [comment]
Hi, I pushed a small update to the demo. Can you try it out?

Notes: 

 * you can set the frequency/times manually, but if you use the keyboard to play sounds it will automatically fill in the frequency/duration you played.
 * When demoing with the keyboard you can play chords, but WAV export just exports a single tone
 * It's kind of non-trivial to figure out how long it takes for the sound to completely die out, so for simplicity I just made it so you manually set the total duration of the exported file.

Let me know how it works out!

**Comment by NeuroNoNeuro** [comment]
> Hi, I pushed a small update to the demo. Can you try it out?
> 
> Notes:
> 
> * you can set the frequency/times manually, but if you use the keyboard to play sounds it will automatically fill in the frequency/duration you played.
> * When demoing with the keyboard you can play chords, but WAV export just exports a single tone
> * It's kind of non-trivial to figure out how long it takes for the sound to completely die out, so for simplicity I just made it so you manually set the total duration of the exported file.
> 
> Let me know how it works out!

Works GREAT!!!  Holy cow, now the sounds are just 'there'.  The 'note duration' and the 'file duration' are accurate as well.  Yep, I can see the non-trivial side of the envelope.  What's nice about the rest of the sound generator is that it leave the user to have the option to experiment with the sound via entering data within the source.  Now, for folks like me, there's a lot less work in actually acquiring the sound.  Export to .WAV and BOOM, there it is.  Saves a few crucial steps.

Thank you so much for this!

**Comment by fenomas** [comment]
Ah cool, let me know if you have issues!

FYI, I made it so the sound starts 0.05 seconds into the file - I'm not sure why, but any less and the attack was getting smushed a little, as if it was fading in. Just in case you're doing any super precise timing etc.

**Comment by NeuroNoNeuro** [comment]
> FYI, I made it so the sound starts 0.05 seconds into the file - I'm not sure why, but any less and the attack was getting smushed a little, as if it was fading in. Just in case you're doing any super precise timing etc.

Yep, noticed that - that's fine - once 'in editor', it's an easy fix.  And I can make the attack even sharper if I want to in a sample editor, so fine by me :D

**Comment by fenomas** [comment]
Cool, I'll mark this closed but let me know if you have issues!
