### ISSUE TITLE
(Firefox 113.0.2) sound plays but in console we see  "SyntaxError: class statement requires a name"

### ISSUE THREAD

**Issue by emirth** [andyhall/wasgen#5]
(Not seeing similar behavior in Chrome)

```javascript
   const Wasgen = await import('wasgen')
   const Gen = Wasgen.default
   const ctx = new AudioContext()
   const gen = new Gen(ctx, ctx.destination, true, true)
   gen.play(
     [   
       {   
         type: 'nb',
         freq: { type: 'sine', freq: 26, gain: { t: 0.47 } },
         gain: { a: 0.1, h: 0, d: 0.1, s: 0.16, r: 0.23 },
         effect: 'shape-boost-4'
       },  
       {   
         type: 'lowpass',
         freq: { t: 7.5, p: 0.3, q: 0.03 },
         Q: 3.4 
       }   
     ],  
     226,
     1,  
     gen.now(),
     gen.now() + 0.25
  )
```
e.g. triggering twice the event that calls this code:

![image](https://github.com/fenomas/wasgen/assets/85695145/206a1a6c-0eae-410e-824e-59eb20cd3c0a)

Would like these not to surface; thanks in advance for any help.

**Comment by fenomas** [comment]
Hi, thanks for reporting. This isn't reproducing for me, but I've seen something similar and I believe it's tied to how you're building and/or minifying your project. Basically, there's a somewhat hairy part of the code that previously could break depending on how it was minified, so I'm guessing that's occurring again.

To nail it down, can you let me know your build setup and post a of what the above reproducing code looks like after it's been built/minified in your environment?

Alternately, I experimented with a (hopefully) more robust version of the code I think is to blame here. I pushed this into a branch `#alt-worker-method`. If you can try that version of wasgen (it's tagged `0.18.4`) it might fix the issue - please let me know if so.

Thanks!

**Comment by emirth** [comment]
Hello and thanks for the reply.

> To nail it down, can you let me know your build setup and post a of what the above reproducing code looks like after it's been built/minified in your environment?

Yes.  The build setup is within the context of Quasar 2.12.0's use of [Vite](https://quasar.dev/quasar-cli-vite/handling-vite#introduction).

> what the above reproducing code looks like after it's been built/minified in your environment

The code defines two separate functions, each calling ```gen.play().```  These are those, pulled out of the code that was written to ```dist/spa``` following a successful build:

Minified...

```javascript
async function jg(e){if(!e.settings.effects)return;const t=await hs();t.play([{type:"nb",freq:{typ    e:"sine",freq:26,gain:{t:.47}},gain:{a:.1,h:0,d:.1,s:.16,r:.23},effect:"shape-boost-4"},{type:"lowpass",freq:{t:7.5,p:.3,q:.03},Q:3.4}],226,1,t.now(),    t.now()+.25)}async function Rg(e){if(!e.settings.effects)return;const t=await hs();t.play([{type:"nb",gain:{a:.1,h:0,d:.1,s:.42,r:.3},effect:"crush-7"    },{type:"lowpass",freq:{t:parseInt(1+"."+pe(1,100)),p:.2,q:.11},Q:1.2}],853,1,t.now(),t.now()+.21)}async function hs(){const t=(await Il(()=>import(".    /index.8a62d3f9.js"),[])).default,n=new AudioContext;return new t(n,n.destination,!0,!0)}async function Ig(e,t){e.webGL&&e.webGL.graphData&&tp(e),awai    t Wg(e,t)}async function Dg(e,t,n)
```
Same minified, but prettified @ DuckDuckGo:

```javascript
async function jg(e) {
    if (!e.settings.effects) return;
    const t = await hs();
    t.play([{
        type: "nb",
        freq: {
            typ e: "sine",
            freq: 26,
            gain: {
                t: .47
            }
        },
        gain: {
            a: .1,
            h: 0,
            d: .1,
            s: .16,
            r: .23
        },
        effect: "shape-boost-4"
    }, {
        type: "lowpass",
        freq: {
            t: 7.5,
            p: .3,
            q: .03
        },
        Q: 3.4
    }], 226, 1, t.now(), t.now() + .25)
}
async function Rg(e) {
    if (!e.settings.effects) return;
    const t = await hs();
    t.play([{
        type: "nb",
        gain: {
            a: .1,
            h: 0,
            d: .1,
            s: .42,
            r: .3
        },
        effect: "crush-7"
    }, {
        type: "lowpass",
        freq: {
            t: parseInt(1 + "." + pe(1, 100)),
            p: .2,
            q: .11
        },
        Q: 1.2
    }], 853, 1, t.now(), t.now() + .21)
}
async function hs() {
    const t = (await Il(() =>
            import (".    /index.8a62d3f9.js"), [])).default,
        n = new AudioContext;
    return new t(n, n.destination, !0, !0)
}
```
If it turns out the above is unhelpful, e.g., you need me to locate more or different code in the built files, just let me know.  Thanks for this library and thanks again for any assistance.

**Comment by fenomas** [comment]
Hi, it looks I would need to see the other file - `index.8a62d3f9.js` - or if that file has imports, it may be elsewhere. If it's large, I believe the offending code should be very close to the string `AudioWorkletProcessor`, which probably only appears once or twice in the bundle, so if you could search for that and post the code around it it would help!

Alternately if you can try building with the alternate branch let me know if it avoids the error.

**Comment by emirth** [comment]
Thank you. I plan to try the other branch soon and will report back in that case.  In the meantime, here is [```index.8a62d3f0.js```](https://gist.github.com/emirth/67bf0f1e87dfcfc3deb406b35d8f3f8d#file-index-8a62d3f9-js-L278) wherein ```AudioWorkletProcessor``` appears.

**Comment by emirth** [comment]
Trying the other branch, I believe this is fixed.  Here's the [equivalent output from the build process](https://gist.github.com/emirth/ee61d5b0a1180b2a45475bbf8c8a986d). 

I plan to wait until a ```0.18.4``` version is released and confirmed as working in my build pipeline before closing this issue, but if you prefer to close it now please feel free.  Thanks for all your help.

**Comment by fenomas** [comment]
Hmm, I wasn't able to reproduce here so I'm not 100% if the alt version fixes the issue. But it should be more robust either way, so I went ahead and pushed it to npm. Please reopen this if it turns out not to fix the issue!
